<a href="https://colab.research.google.com/github/AimjGuytidy/Neural_network/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensorflow

In [ ]:
#import tensorflow
import tensorflow as tf
#check the version
print(tf.__version__)

2.6.0


#### Creating tensors with `tf.constant`

In [ ]:
#create a scalar with tf.constant
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
#check the dimension of scalar
scalar.ndim 

0

In [ ]:
#create a vector with tf.constant
vec = tf.constant([12,45,36,87])
vec

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 45, 36, 87], dtype=int32)>

In [ ]:
#check the dim of vec
vec.ndim

1

In [ ]:
#create a matrix with tf.const
matry = tf.constant([[1,2,3],
                     [4,5,6],
                     [7,8,9]]) #we created a 3 x 3 matrix
matry

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:

#check dim of matry
matry.ndim

2

In [ ]:
#let's create a matrix of float dtype
matr = tf.constant([[1.,2.,3.,4.],
                    [2.,42.,78.,46.]],dtype = tf.float16) #we used 16 instead of 32 to save memory
matr


<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 2., 42., 78., 46.]], dtype=float16)>

In [ ]:
#let's check the dim of matr
matr.ndim

2

In [ ]:
#let's create a tensor with tf.const
tensory = tf.constant([[[1,2,3],[4,5,6]],
                       [[2,3,4],[7,6,9]],
                       [[5,6,9],[4,8,2]]])
tensory


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 4],
        [7, 6, 9]],

       [[5, 6, 9],
        [4, 8, 2]]], dtype=int32)>

In [ ]:
#check the dim of tensory
tensory.ndim

3

#### Creating tensors with `tf.Variable` and checking the difference btwn `tf.Variable` and `tf.constant`

In [ ]:
#creating a vector with tf.Variable
vectori = tf.Variable([4,6,78])
vectori

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 4,  6, 78], dtype=int32)>

In [ ]:
#check the dimension of vectori
vectori.shape

TensorShape([3])

In [ ]:
# trying to assign new values to our vector elements we created with tf.const vs tf.Var

#vec[1].assign() #doesn't work for tf.constant elements
vectori[2].assign(12)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([ 4,  6, 12], dtype=int32)>

the main difference between tf.constant and tf.Variable is that we can change the values of the elements in tf.Variable variables while we can't do the same for tf.constant

#### Creating random tensors

In [ ]:
#first we create an object
randomy = tf.random.Generator.from_seed(42)
#we create our first random tensor
rando1 = randomy.normal(shape=(3,2))
rando1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
#let's check if the seed method works
rando2 = randomy.normal(shape=(3,2))
rando1,rando2,rando1 == rando2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896016],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
#let's check if the seed method works
randoma = tf.random.Generator.from_seed(42)
rando2 = randoma.normal(shape=(3,2))
rando1,rando2,rando1 == rando2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#### Shuffling our tensors

In [ ]:
rando = tf.random.Generator.from_seed(42)
shuffler1 = tf.constant([[1,3],
                         [4,8],
                         [8,7],
                         [5,6]])
shuffler2 = rando.uniform(shape = (4,2),minval=4,maxval=19,dtype=tf.int32)
shuffler1,shuffler2 

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 3],
        [4, 8],
        [8, 7],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 7, 16],
        [10,  7],
        [10, 10],
        [ 5, 16]], dtype=int32)>)

In [ ]:
tf.random.set_seed(42)
testy = tf.random.uniform(shape=(2,2),seed=42)
testy

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.4163028 , 0.26858163],
       [0.47968316, 0.36457133]], dtype=float32)>

In [ ]:
#shuffle our variables
#we set a global seed
tf.random.set_seed(42)
shufd1 = tf.random.shuffle(shuffler1, seed=42)
shufd2 = tf.random.shuffle(shuffler2, seed=42)
shufd1,shufd2

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[4, 8],
        [8, 7],
        [1, 3],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 7, 16],
        [10, 10],
        [ 5, 16],
        [10,  7]], dtype=int32)>)

### other ways to create tensors

In [ ]:
#using ones
ony = tf.ones(shape=(3,3))
ony


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
#using zeros
zery = tf.zeros([3,3])
zery

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:

#create identity matrix
idy = tf.eye(3)
idy

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

#### turning numpy arrays to tensors


In [ ]:
#import numpy
import numpy as np
np_A = np.arange(1,13,dtype=np.int32)
A = tf.constant(np_A)
B = tf.constant(np_A,shape=(3,4))
B1 = tf.constant(np_A,shape=(2,6))
B2 = tf.constant(np_A,shape=(6,2))
C = tf.Variable(np_A)
np_A, A, B, C,B1,B2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32),
 <tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(12,) dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(6, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

The difference between `numpy` and `tensorflow` is that tensors can run on **GPU** which can make them faster 

#### Getting info from tensors

In [ ]:
#create an only ones tensor of n dimensional
maty = tf.ones([3,3,4])
maty

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
#let's print all info we can get
print("size of maty:",tf.size(maty))
print("size of maty:",tf.size(maty).numpy())
print("shape of maty:",maty.shape)
print("dimension of maty:",maty.ndim)
print("elements along axis 0 of maty:",maty.shape[0])
print("elements along the last axis of maty:",maty.shape[-1])
print("datatype of maty:",maty.dtype)

size of maty: tf.Tensor(36, shape=(), dtype=int32)
size of maty: 36
shape of maty: (3, 3, 4)
dimension of maty: 3
elements along axis 0 of maty: 3
elements along the last axis of maty: 4
datatype of maty: <dtype: 'float32'>


#### Tensor indexing

In [ ]:
#get first two elements of each dim of maty
maty[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [ ]:
#create a rank 4 tensor
ra4 = tf.ones([3,3,4,4])
ra4,ra4.ndim,ra4.shape

(<tf.Tensor: shape=(3, 3, 4, 4), dtype=float32, numpy=
 array([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 

In [ ]:
#let's print all info we can get
print("size of ra4:",tf.size(ra4))
print("size of ra4:",tf.size(ra4).numpy())
print("shape of ra4:",ra4.shape)
print("dimension of ra4:",ra4.ndim)
print("elements along axis 0 of ra4:",ra4.shape[0])
print("elements along the last axis of ra4:",ra4.shape[-1])
print("datatype of ra4:",ra4.dtype)

size of ra4: tf.Tensor(144, shape=(), dtype=int32)
size of ra4: 144
shape of ra4: (3, 3, 4, 4)
dimension of ra4: 4
elements along axis 0 of ra4: 3
elements along the last axis of ra4: 4
datatype of ra4: <dtype: 'float32'>


In [ ]:
#indexing tensors is like indexing in python
ra4[:,:2,:2,:-1]

<tf.Tensor: shape=(3, 2, 2, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

In [ ]:
#get the first element from each index except the last one
ra4[0,0,0,:]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [ ]:
ra4[0]

<tf.Tensor: shape=(3, 4, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
ra4[:][2]

<tf.Tensor: shape=(3, 4, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
ra4,ra4[:][2][1]

(<tf.Tensor: shape=(3, 3, 4, 4), dtype=float32, numpy=
 array([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 

In [ ]:
ra4,ra4[:][2][1][1]

(<tf.Tensor: shape=(3, 3, 4, 4), dtype=float32, numpy=
 array([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 

In [ ]:
idy,idy.shape,idy.ndim

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32)>, TensorShape([3, 3]), 2)

In [ ]:
#get the last item of each row
idy[:,-1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 1.], dtype=float32)>

In [ ]:
#add in extra dimension
idy3 = tf.reshape(idy,[3,1,3])
idy3,idy3.shape,idy3.ndim

(<tf.Tensor: shape=(3, 1, 3), dtype=float32, numpy=
 array([[[1., 0., 0.]],
 
        [[0., 1., 0.]],
 
        [[0., 0., 1.]]], dtype=float32)>, TensorShape([3, 1, 3]), 3)

In [ ]:
idy31 = tf.reshape(idy,[3,3,1])
idy31,idy31.shape,idy31.ndim

(<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [0.],
         [0.]],
 
        [[0.],
         [1.],
         [0.]],
 
        [[0.],
         [0.],
         [1.]]], dtype=float32)>, TensorShape([3, 3, 1]), 3)

In [ ]:
#other ways than tf.reshape
#using tf.newaxis
idy32 = idy[...,tf.newaxis]
idy32,idy32.shape,idy32.ndim

(<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [0.],
         [0.]],
 
        [[0.],
         [1.],
         [0.]],
 
        [[0.],
         [0.],
         [1.]]], dtype=float32)>, TensorShape([3, 3, 1]), 3)

In [ ]:
#other ways than tf.reshape
#using tf.expand_dims
idy33 = tf.expand_dims(idy, axis=-1)
idy33,idy33.shape,idy33.ndim

(<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [0.],
         [0.]],
 
        [[0.],
         [1.],
         [0.]],
 
        [[0.],
         [0.],
         [1.]]], dtype=float32)>, TensorShape([3, 3, 1]), 3)

In [ ]:
idy4 = tf.expand_dims(idy, axis=0)
idy4,idy4.shape,idy4.ndim

(<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
 array([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]], dtype=float32)>, TensorShape([1, 3, 3]), 3)

#### Manipulating tensors

**Basic Operations**

In [ ]:
#tensor addition
didu = tf.constant([[4,6],
                    [7,8]])
didu + 12

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 18],
       [19, 20]], dtype=int32)>

In [ ]:
#using tensor built-in functions will speed up the process when using GPU faster than using basic operations
tf.math.add(didu,12)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 18],
       [19, 20]], dtype=int32)>

In [ ]:

didu - 4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 2],
       [3, 4]], dtype=int32)>

In [ ]:

didu * 8

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 48],
       [56, 64]], dtype=int32)>

In [ ]:

tf.math.multiply(didu,8)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 48],
       [56, 64]], dtype=int32)>

#### Matrix Multiplication

In [ ]:
d0 = tf.constant([[1,2,5],
                  [7,2,1],
                  [3,3,3]])
d1 = tf.constant([[3,5],
                  [6,7],
                  [1,8]])
tf.matmul(d0,d1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#matrix multiplication using @
d0 @ d1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#usage of tf.transpose
d1 @ tf.transpose(d1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]], dtype=int32)>

In [ ]:

tf.linalg.matmul(d1,tf.transpose(d1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]], dtype=int32)>

In [ ]:
#using tf.tensordot
tf.tensordot(d1,tf.transpose(d1),axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]], dtype=int32)>

#### Change the datatype of tensor

In [ ]:
#changing data types using tf.cast, as in sql!!!
d0.dtype

tf.int32

In [ ]:

da = tf.cast(d0, dtype=tf.int16)
da

<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int16)>

In [ ]:
do = tf.cast(d1, dtype=tf.float16)
do

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 5.],
       [6., 7.],
       [1., 8.]], dtype=float16)>

In [ ]:
tf.random.set_seed(42)
de = tf.random.normal([3,2],seed=42)
de

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.3148774 , -0.15421568],
       [ 0.91138786, -0.7991441 ],
       [-0.10875293,  0.28436786]], dtype=float32)>

In [ ]:

dey = tf.cast(de,dtype=tf.int16)
dey

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 0],
       [0, 0],
       [0, 0]], dtype=int16)>

#### Aggregating tensors

In [ ]:
didu

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [7, 8]], dtype=int32)>

In [ ]:
dede = tf.cast(didu,dtype=tf.float16)

In [ ]:
tf.abs(-didu)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [7, 8]], dtype=int32)>

In [ ]:
#find the mean of each row of didu
tf.reduce_mean(dede,axis = 0)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([5.5, 7. ], dtype=float16)>

In [ ]:
tf.reduce_mean(dede,axis = 1)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([5. , 7.5], dtype=float16)>

In [ ]:
#look for min numnber
tf.reduce_min(dede,axis = 1)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4., 7.], dtype=float16)>

In [ ]:
tf.reduce_min(dede,axis = 0)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4., 6.], dtype=float16)>

In [ ]:
#let's do sums
tf.reduce_sum(dede, axis = 0)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([11., 14.], dtype=float16)>

In [ ]:
#let's find the sd and var
tf.math.reduce_std(dede)

<tf.Tensor: shape=(), dtype=float16, numpy=1.4795>

In [ ]:
tf.math.reduce_variance(dede)

<tf.Tensor: shape=(), dtype=float16, numpy=2.188>

In [ ]:
1.4795**2

2.1889202500000002

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(didu,sample_axis=None)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tfp.stats.variance(dede,sample_axis=None)

<tf.Tensor: shape=(), dtype=float16, numpy=2.188>

In [ ]:
tfp.stats.stddev(didu,sample_axis=None)

InvalidArgumentError: ignored

In [ ]:
tfp.stats.stddev(dede,sample_axis=None)

In [ ]:
tf.math.reduce_std(didu)

#### Find the positional maximum and minimum

In [ ]:
#let's find the index at which the maximum value is (argmax)
tf.math.argmax(dede,axis = 1)

In [ ]:
dede

In [ ]:
tf.math.argmin(dede,axis = 0)

watch vid 25

In [ ]:
tf.math.argmin(dede)

In [ ]:
tf.math.argmin(tf.reshape(dede,(tf.size(dede),1)))

In [ ]:
dede.shape

In [ ]:
tf.size(dede)

In [ ]:
tf.math.argmax(tf.reshape(dede,(tf.size(dede),1)))

In [ ]:
tf.math.argmax(tf.reshape(dede,(tf.size(dede),1))).numpy().tolist()

#### Squeezing tensors
This is done to remove all extra 1 dimension in our tensor shape

In [ ]:
tf.random.set_seed(42)
gety = tf.constant(tf.random.uniform(shape=[50]),shape=[2,1,1,1,25])
gety

In [ ]:
#let us see what squeeze does
gety_sq = tf.squeeze(gety)
gety_sq

#### One-hot encoder
this is the same as we have seen in sklearn!!

In [ ]:
#create a list
yupi = ['ikarita','ihene','ipusi','ikiyiko']

In [ ]:
kaka = tf.constant(yupi)
kaka

In [ ]:
np.array(yupi)

In [ ]:
#let's turn our list in numeric values
for dep in range(9):
  print(tf.one_hot([4,5,7,7,6,2],depth=dep))

In [ ]:
for dep in range(9):
  print(tf.one_hot([4,5,7,7,6,2],depth=dep,on_value="yes",off_value="0"))

#### square, sqrt and log

In [ ]:
tiku = tf.range(1,12)
tiku

In [ ]:
tf.math.square(tiku)

In [ ]:
tf.math.sqrt(tf.cast(tiku,dtype=tf.float32))

In [ ]:
tf.math.log(tf.cast(tiku,dtype=tf.float32))

#### Tensors and Numpy

In [ ]:
numy = np.arange(1,4)
tfy = tf.constant(numy)
tfy1 = tf.constant([2,4,5,3,7])
numy,tfy,tfy1

### Getting access to a GPU

In [ ]:
#let's check which unit we are using
tf.config.get_visible_devices()

let us try get access to a GPU from colab

after setting a GPU we have to import tensorflow again

In [ ]:
!nvidia-smi

### Solving some exercises

In [ ]:
sca = tf.constant(7)
mat = tf.constant([[1,2],
                   [4,3]])
vec = tf.constant([1,2,5,6])
tens = tf.constant(tf.random.uniform([2,2,2,4]))
sca,mat,vec,tens

In [ ]:
sca.shape,tf.size(sca),sca.ndim,mat.shape,tf.size(mat),mat.ndim,vec.shape,tf.size(vec),vec.ndim,tens.shape,tf.size(tens),tens.ndim

In [ ]:
tensy = tf.random.uniform([5,300],maxval=1)
tenso = tf.random.uniform([5,300],maxval=1)
tensy,tenso

In [ ]:
tf.linalg.matmul(tensy,tf.transpose(tenso))

In [ ]:
tf.tensordot(tensy,tf.transpose(tenso), axes=1)

In [ ]:
tete = tf.random.uniform([224,224,3],maxval=1)
tete

In [ ]:
tf.reduce_max(tete,axis=0), tf.reduce_min(tete,axis=0)

In [ ]:
tutu = tf.random.uniform([1,224,224,3],maxval=1)
tutu

In [ ]:
tf.squeeze(tutu)


In [ ]:
turi = tf.range(10)
turi.shape

In [ ]:
tf.argmax(turi)

In [ ]:
depth = 10
tf.one_hot(turi,depth)

#### lets look at cosine

In [ ]:
#we use tf.math.cos()
cosy = tf.random.uniform([7])
tf.math.cos(cosy)

In [ ]:
mnist = tf.keras.datasets.mnist
# mnist.load_data()

In [ ]:
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [ ]:
X_train.shape

In [ ]:
X_train[-2,-4:,-4:]

In [ ]:
tf.argmax(tf.reshape(X_train,[-1]))

In [ ]:
tf.reshape(X_train,[-1]).shape

In [ ]:
6*28*28

let us convert the datasets from integers to floating 

In [ ]:
X_test,X_train = X_test/255.0,X_train/255.0 

In [ ]:
X_test.shape

In [ ]:
tf.size(X_test)

In [ ]:
X_test.dtype

In [ ]:
y_test.shape

let's create our first model with keras

In [ ]:
model = tf.keras.Sequential([
                             tf.keras.layers.Flatten(input_shape=(28,28)),
                             tf.keras.layers.Dense(128,activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(10)
])

In [ ]:
preds = model(X_train[:1])
preds.numpy()

In [ ]:
#let's turn them into probability
tf.nn.softmax(preds).numpy()

In [ ]:
#let's evaluate our model by creating a loss fct to evaluate our preds based on real values
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
#let's check out the losses
loss_fn(y_train[:1],preds).numpy()

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics = ['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=6)

In [ ]:
model.evaluate(X_test,y_test,verbose=2)

In [ ]:
proby = tf.keras.Sequential([
                             model,
                             tf.keras.layers.Softmax()
])

In [ ]:
proby(X_test[:3])

In [ ]:
import numpy as np

In [ ]:
xy = np.arange(1,9) 
xy

In [ ]:
xy.mean()

In [ ]:
np.median(xy)

In [ ]:
(xy*0.05).mean()

In [ ]:
4.5*0.05

In [ ]:
np.median(xy*0.05)

In [ ]:
xy.std()

In [ ]:
(xy*0.05).std()

In [ ]:
2.29128784747792*0.05

In [ ]:
check1 = ['learn','quiz','practice','contribute']
check2 = check1
check3 = check1[:]

check2[0] = 'code'
check3[1] = 'mcq'

count = 0
for c in (check1,check2,check3):
  if c[0] == 'code':
    count += 1
  if c[1] == 'mcq':
    count += 10
print(count)

In [ ]:
check3,check2

In [ ]:
check1